run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nilerr
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usetesting
